blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns=[
    path('',views.allblogs,name='allblogs'),
    path('<int:blog_id>/',views.detail,name='detail')
]

jobs/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.home,name='home')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
import jobs.views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',jobs.views.home,name='home'),
    path('blog/',include('blog.urls'))
    

    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class blog(models.Model):
    title = models.CharField(max_length=260)
    pub_date = models.DateTimeField()
    image = models.ImageField(upload_to='image/')
    body = models.TextField()
    
    def summary(self):
        return self.body[:100]

    def pub_date_preety(self):
        return self.pub_date.strftime('%b,%e,%y')

    def __str__(self):
        return self.title

jobs/models.py
from django.db import models

# Create your models here.
class  job(models.Model):
    image = models.ImageField(upload_to='images/')
    summary = models.CharField(max_length=200)
    

blog/views.py
from django.shortcuts import render,get_object_or_404
from . models import blog
# Create your views here.
def allblogs(request):
    blogs=blog.objects.all()
    return render(request,'blog/allblogs.html',{'blogs':blogs})

def detail(request,blog_id):
    blogdetail =blog.objects.get(id=blog_id)
    return render(request,'blog/detail.html',{'blogdetail':blogdetail})

jobs/views.py
from django.shortcuts import render
from . models import job
# Create your views here.
def home(request):
    jobs = job.objects.all()
    return render(request,'jobs/home.html',{'jobs':jobs})

blog/templates/blog/allblogs.html
<!doctype html>
<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Album example · Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{% url 'home' %}">zUnAiD</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
              <a class="nav-item nav-link " href="https://twitter.com/@Zunaidarmy">Twitter </a>
              <a class="nav-item nav-link" href="{% static 'resume.pdf' %}">Resume</a>
              <a class="nav-item nav-link" href="{% url 'blog:allblogs' %}">Blog</a>
             
            </div>
          </div>
        </nav>
    </header>

<main role="main">
<div class="container">
  <h1 class="text-center" pt-3>Zunaid Blog</h1>
  <br/><br/>
  <h2>Latest Posts</h2>
  <hr>
  {% for blog in blogs %}
  <a href="{% url 'blog:detail' blog.id %}">
<h3>{{blog.title.upper}}<br/></h3>
<h6>{{blog.pub_date_preety}}</h6>
<img class="img-fluid" src="{{blog.image.url}}" height="200" width="200"><br/>
<p>{{blog.summary}}</p></a>

  {% endfor %}
</div>
  </main>
<footer class="text-muted">
  <div class="container text-center">
        &copy; zunaid, {% now "Y" %}
    
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

blog/templates/blog/detail.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Album example · Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">zUnAiD</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link " href="#">Twitter </a>
            <a class="nav-item nav-link" href="#">Resume</a>
            <a class="nav-item nav-link active" href="#">Blog</a>
           
          </div>
        </div>
      </nav>
    </header>

<main role="main">
<div class="container">
        {{blogdetail.title}}</br>
        {{blogdetail.pub_date}}</br>
        <img src="{{blogdetail.image.url}}" height="300px" width="400px"><br>
        {{blogdetail.body}}
</div>
  </main>
<footer class="text-muted">
  <div class="container text-center">
        &copy; zunaid, {% now "Y" %}
    
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

jobs/templates/jobs/home.html
<!doctype html>
<html lang="en">
  {% load staticfiles %}
  
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Album example · Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">zUnAiD</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link " href="https://twitter.com/@Zunaidarmy">Twitter </a>
            <a class="nav-item nav-link" href="{% static 'resume.pdf' %}">Resume</a>
            <a class="nav-item nav-link" href="{% url 'blog:allblogs' %}">Blog</a>
           
          </div>
        </div>
      </nav>
    </header>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Hi ! I am zunaid</h1>
      <p class="lead text-muted">Hey i am zunaid khan .and i am from india and love to work with django and backend and bootstrap as frontend.</p>
      <p>
        <a href="mailto:mdzunaidkhan00@gmail.com" class="btn btn-primary my-2">Email me</a>
      </p>
      <img src="{% static 'aa.jpg' %}" height="300px" width="350px">
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        
        {% for job in jobs.all %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="{{job.image.url}}">
            <div class="card-body">
              <p class="card-text">{{job.summary}}</p>
            </div>
          </div>
        </div>
       {% endfor %}              
      </div>
    </div>
  </div>
        
</main>

<footer class="text-muted">
  <div class="container text-center">
        &copy; zunaid, {% now "Y" %}
    
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>